language: go
go:
    - 1.9
#    - tip

go_import_path: github.com/Versent/saml2aws

install:
    - echo noop

env:
    - "PATH=/home/travis/gopath/bin:$PATH"

script:
    - make test

matix:
    fast_finish: true
    allow_failures:
        - go: tip
