skip_non_tags: true
image: Visual Studio 2019
clone_folder: c:\gopath\src\github.com\versent\saml2aws
environment:
  GOPATH: c:\gopath
  CHOCOLATEY_APIKEY:
    secure: 3kWTz99Qj+ipyaR73CxcJeGRRbmk84MF2ERDu6MyY10cjHAi6s3AVZ2Ccoa+Ioyt
  appName: saml2aws
install:
- set PATH=C:\msys64\mingw64\bin;C:\go121\bin;%PATH%
- set GOROOT=C:\go121
- ps: >-
    $VerbosePreference = 'Continue'

    write-output $env:GOPATH

    write-output $env:APPVEYOR_REPO_TAG_NAME

    write-output $env:APPVEYOR_REPO_TAG_NAME.Split('v')[1]

    write-output $env:GOROOT

    $env:Path += ";`"$env:GOPATH\bin`";c:\go\bin;"

    write-output $env:PATH

    go version

    go env

    Install-PackageProvider -Name NuGet -Force

    Install-Module InvokeBuild -Force
build_script:
- cmd: go mod download
- ps: >-
    Invoke-Build
test_script:
- cmd: go test -v .

artifacts:
- path: $(appName).zip
- path: $(appName).zip.sha256
- path: 'choco/$(appName).*.nupkg'
- path: 'choco/$(appName).*.nupkg.sha256'
#deploy:
#- provider: GitHub
#  release: saml2aws-$(appveyor_build_version)
#  auth_token:
#    secure: kxO8LOQfcXH15OdilgteFKRn4Y7vUQND84WaR2fgghgiwTTHPLgKV1j+6o/8Ggjx
#  artifact: saml2aws.zip, saml2aws.zip.sha256, choco/saml2aws.1.3.2.nupkg, choco/saml2aws.1.3.2.nupkg.sha256
#  draft: true
deploy_script:
- ps: >-
    choco apiKey -k $env:CHOCOLATEY_APIKEY -s https://push.chocolatey.org/

    choco push ./choco/${env:appName}.$(($env:APPVEYOR_REPO_TAG_NAME).Split('v')[1]).nupkg -s https://push.chocolatey.org/
